### ISSUE TITLE
http://administrator.frozennode.com/ doesn't load any more

### ISSUE THREAD

**Issue by t202wes** [FrozenNode/Laravel-Administrator#1038]
http://administrator.frozennode.com/ doesn't load any more

**Comment by janhartigan** [comment]
I'll use this issue to mention that I am no longer maintaining this repository because turning it into what it should be will take more time than I have.

It's also worth reiterating that this repo is under an MIT license, which means anybody has the right to do anything they want with it. You can fork it, recreate it under a different name, etc.

The docs have always been available in the [`/docs`](https://github.com/FrozenNode/Laravel-Administrator/tree/master/docs) directory and anybody can rebuild them any time they want.
