### ISSUE TITLE
Error on Custom Validations

### ISSUE THREAD

**Issue by pettercastro** [FrozenNode/Laravel-Administrator#699]
I am using a custom validator with the rule 'max_depth' by defining a resolver from within a Service Provider, just like explained here:

http://www.sitepoint.com/data-validation-laravel-right-way-custom-validators/

The rule works fine when I call the method **store** manually, however when I try to save the same object from within the Laravel Administrator, the method 'validateMaxDepth' is not recognized. Do you support custom validations? If not, what would be the solution to this problem?

**Comment by jmichaelterenin** [comment]
Hi Jan,
Not sure if you are still contributing to this project, but custom validators which use parameters which are part of the model to validate 'updates' (existing model) do not work. This is primarily because you're using Administrator's validator and when it comes time to update the rule with data from the model in "beforeValidate", the validation has already completed. Additionally, updates to data remove any non-dirty data from the model, so a manual call to "beforevalidate" has to occur before your array_intersect_key() of the rules and the data inside Config::save(...);
