### ISSUE TITLE
save

### ISSUE THREAD

**Issue by amirmasoud** [FrozenNode/Laravel-Administrator#708]
when I try to save a new item it return 404 response.
It tries to access `admin/{model}//save` (2 slashes).
and so return a 404 error.
I have no extra routes on this model and also for other models the problem exists, but delete and update works fine.
How can I fix it?

**Comment by chriscarpo** [comment]
I just had the same problem with creating new records, and found out that it's because of including the ID in the edit_fields, even though it's not editable. If I remove that field, new items save correctly without an error.

When looking at the save URL, if the ID field is included, there is none, so there is 2 forward slashes in the URL "model//save" . If that field is removed, the URL then has 0 as the ID, "model/0/save"

**Comment by chriscarpo** [comment]
Just realised after writing the previous comment that you can just put 'value' => 0 to give a default value to the ID and then it works fine.
