### ISSUE TITLE
How to create relationship image field in edit form?

### ISSUE THREAD

**Issue by prady00** [FrozenNode/Laravel-Administrator#744]
I have products hasMany images. I tried in product model config.

```
'image' => array(
            'title' => 'Image',
            'type' => 'image',
            'name_field' => 'path',
            'location' => public_path() . '/uploads/products/originals/',
            'naming' => 'random',
            'length' => 20,
            'size_limit' => 2,
            'sizes' => array(
                array(65, 57, 'crop', public_path() . '/uploads/products/thumbs/small/', 100),
                array(220, 138, 'landscape', public_path() . '/uploads/products/thumbs/medium/', 100),
                array(383, 276, 'fit', public_path() . '/uploads/products/thumbs/full/', 100)
            )
        ),
```

How can I create image field which gets saved in images table ?

**Comment by janhartigan** [comment]
@devonatdomandtom sorry for the delayed response. Let's say you have a `Dogs` table and an `Images` table. Dogs have many images, an image belongs to a dog. Since it's not possible to create a hasMany field on the dogs config, you need to create a belongs to dog field on the images config. That is to say, make a model specifically for dog images, create a config for it, and select the dog from a list of dogs in that config. Because there's a limitation in Administrator, you have to think about it from the other side.
