### ISSUE TITLE
Custom view page - example please

### ISSUE THREAD

**Issue by paulsbroomfield** [FrozenNode/Laravel-Administrator#800]
Hi guys,

I'm struggling with getting custom view to work - I just don't know where to place the code or how to name the files...

Could you create an example please, or add a bit more detail to:
http://administrator.frozennode.com/docs/configuration

Thanks!
Paul

**Comment by royisme** [comment]
https://github.com/summerblue/laravel-blog this is base on Laravel-Administrator, you can try edit some to run

**Comment by paulsbroomfield** [comment]
Hi roisme, Thanks for your reply :) I should have explained a bit more. I'm using FrozenNode as the back end to the site I have almost finished.

The site is for a design company that wants to be able to control the content of each of the pages as well as upload work case studies - the features are so custom a word press theme wouldn't work - plus I wanted to learn Laravel.

Its a great crud interface, but one of my tables has a lot of columns that need filling in - its for work case studies - so these columns look confusing when next to each over. I would like to either create a custom admin view, or attach some JS/CSS to help with the layout.

any tips will be very helpful :)

thanks!

**Comment by royisme** [comment]
hi paul,
  I think you may change to use other like pingpong/admin , Laravel-Administrator not a support custom view, it like juse use to manage a little table. I advice use a cms that base on Laravel . hope it can help you.

**Comment by janhartigan** [comment]
There actually is a custom view feature that you can read about here:

http://administrator.frozennode.com/docs/configuration#menu

However, it doesn't give you access to any of the normal stuff you'd find in Administrator. It's just a basic page.

@royisme thanks for sharing that repo. Worth mentioning that you can use simple boolean values instead of closures in [action permissions](https://github.com/summerblue/laravel-blog/blob/master/app/config/administrator/comments.php#L10-L13).
