### ISSUE TITLE
Upgrading to Laravel 5

### ISSUE THREAD

**Issue by gabarba** [FrozenNode/Laravel-Administrator#811]
I was wondering if there was anything in the pipeline for supporting Laravel 5. I have been mucking around trying to make it work and updating parts as the errors arise to make it work for my needs but before I continue any further I was wondering if this is something you have already started working on or have plans to work on in the near future.

**Comment by javichito** [comment]
Same here.

**Comment by janhartigan** [comment]
I haven't started working on this and I have no plans anytime soon. Work has made it difficult to continue contributing much time to this project. In principle, it shouldn't be too difficult if you feel like putting together a PR. The things that immediately jump out at me:

- Filters need to be converted into middleware
- Routes need to use middleware instead of filters
- Controllers need to be reworked a bit

There might be a few other bugs here and there in the query building, but I suspect most of that will be ok.

**Comment by gabarba** [comment]
Yea no problem I understand, I'm kinda on the same boat at the moment. Currently working on converting my app over to Laravel 5 as well so hopefully after I am done with that which should be in the next day I can start working on a Laravel 5 PR. 

I do have to say that I happen to love your implementation of a Laravel CRUD backend the best. I do hope to contribute more to your project in my free time in the near future.

**Comment by happyDemon** [comment]
I submitted a PR,
I had to rework the ServiceProvider a bit, along with the controller and views (for config references) and added Middleware.

It seems to work for light use, haven't gotten into testing it.

**Comment by janhartigan** [comment]
As time goes on, my company is using Administrator more and more. So possibly sometime in the next ~6 months I'll be able to dedicate a lot of time to a complete rework of Administrator getting in a lot of features that are missing. Can't promise anything, but that's my goal.

**Comment by janhartigan** [comment]
It's now upgraded to Laravel 5. Please let me know if there are any bugs.

**Comment by bradis** [comment]
Hello please with laravel 5.1 you can make a simple custom page sample because always I got this error Administrator: You must provide a valid menu item in the home_page option of your config

**Comment by vad11** [comment]
I give blank page with laravel 5. I see html page code , its seen ok.
