### ISSUE TITLE
Custom pages with controllers

### ISSUE THREAD

**Issue by benallfree** [FrozenNode/Laravel-Administrator#819]
Not sure if this is a common request, but I'd like to integrate my own custom pages into Administrator. Custom pages with their own controllers and actions, but maintain the administrator menu bar and footer.

I can get a custom 'page' working, but it's really just a view. I am looking for a way to add a custom controller with actions too. Is there a recommended approach for this?

**Comment by janhartigan** [comment]
Administrator just sits next to your application, it doesn't replace it. If you can get a [custom page working with your own JS and CSS](http://administrator.frozennode.com/docs/configuration#menu), then you can point it at any controller you want in your application.

**Comment by benallfree** [comment]
Thank you, is there an example of how to point it at any controller? That's the part I don't understand how to do.

**Comment by janhartigan** [comment]
Administrator will render the page for you, but the rest is up to you. It's just a matter of writing some JavaScript that communicates with a route/controller you've created in your application.

**Comment by wearetheroyals** [comment]
Hi,

Just to expand on this for anyone who comes along. Administrator appears to include any file in the config/administrator folder - it will render the contents before the HTML tag - not sure if that is intentional or not.

But to display a custom view, add something similar to the below to your menu config in administrator.php:

'page.admin.test'

This will include the page in resources/views/admin/test.php 

Then as Jan says, write some JS to ajax in the content from your route.

hth.
