### ISSUE TITLE
Edit hidden fields in model

### ISSUE THREAD

**Issue by mrwogu** [FrozenNode/Laravel-Administrator#843]
Hello, I got in my model:
```php
public $hidden = array('password', 'notes');
```
and in my admin model configuration:
```php
'edit_fields' => array(
	'password' => array(
		'type' => 'password',
		'title' => 'Password'
	),
	'notes' => array(
		'title' => 'Admin Notes',
		'type' => 'textarea'
	)
)
```
With above code, i cannot see or set values in these fields. How can i do it?

**Comment by stevenbouma** [comment]
A workaround that I've used:

```php
// example class
class SomeClass extends Model
{
   protected $hidden = array('password', 'notes');  
   ...
}
```

```php
// Then define this model for use with laravel administrator only:
// here you can reset $hidden / $appends / $visible etc. to default values

class AdminSomeClass extends SomeClass {
    protected $hidden = [];

    // set the table name to match your original class, otherwise the class name is used for autonaming
    protected $table = 'some_class'; 

}
```

**Comment by Hazzard13** [comment]
This seems like a problem that could be solved on the developer's end. It looks like the display list uses the object with accessors, because my hidden fields are displayed perfectly. And in the edit, editing fields actually does work, but when it loads the information into the admin fields, it uses a to_json or something else affected by $hidden, because hidden fields load in as blank, causing a huge issue for admins where it's easy to accidentally delete data by saving these empty fields while editing something else. If the edit_fields loaded their data the same as the display list, this wouldn't be a problem at all. 

For now though, I think stevenbouma is right, and the only workaround is to create a separate model for admin use.
