### ISSUE TITLE
Crash on Laravel 5 when using config::cache

### ISSUE THREAD

**Issue by pelletiermaxime** [FrozenNode/Laravel-Administrator#871]
`PHP Fatal error: Call to undefined method Closure::__set_state()`

I found a very similar bug report on another l5 package https://github.com/efficiently/authority-controller/issues/27.

Thanks for the great package !

**Comment by davemathews** [comment]
Ok so the workaround to this is that the permission closure in the administrator.php config can be a string to a helper function or class method that can be called. So if you do that then your config::cache will work.  Closure caching is not supported by Laravel's cacheing as it is expensive to keep serializing and unserializing the config, and defeats the purpose of the cache.

helpers.php
```php
function authorize_admin()
{
    return Auth::check();
}
```
administrator.php
```php
'permission'=> 'authorize_admin',
```

**Comment by jmichaelterenin** [comment]
#davematthews, I did as you instructed, because an update to Laravel 5.4.24 is now enforcing this for me.

here is my helpers.php:

```
<?php

function authorize_admin()
{
	return \Auth::check();
}
```

Here is my updated composer.json (snippet):
 
```
"autoload" : {
		"classmap" : [
			"database"
		],
		"psr-4" : {
			"App\\" : "app/",
			"MyApp\\" : "app/MyApp/"
		},
		"files": ["app/Helpers/helpers.php"] // <- this line was added
	},
```
and here is my updated administrator.php (snippet):

`'permission'=> 'authorize_admin',`

But now I'm getting:
exception 'InvalidArgumentException' with message 'There are problems with your administrator.php config: The permission option must be a function' in C:\xampp\htdocs\tikitour\vendor\exodusanto\administrator\src\Frozennode\Administrator\Config\Factory.php:106

I've cleared the config cache, performed a composer dump-autoload ... ?
